import { GeneratorConfig } from '../types';
import { BASE_IOS_LIST } from '../data/ciosData';

export function calculateHexMajor(major: number): string {
  const b0 = (major >> 24) & 0xff;
  const b1 = (major >> 16) & 0xff;
  const b2 = (major >> 8) & 0xff;
  const b3 = major & 0xff;
  const hex = (b: number) => '0x' + b.toString(16).padStart(2, '0');
  return `${hex(b0)},${hex(b1)},${hex(b2)},${hex(b3)}`;
}

export function calculateHexMinor(minor: string): string {
  const parts: string[] = [];
  for (let i = 0; i < 16; i++) {
    const code = i < minor.length ? minor.charCodeAt(i) : 0;
    parts.push('0x' + code.toString(16).padStart(2, '0'));
  }
  return parts.join(',');
}

export function generateCiosMapsXml(config: GeneratorConfig): string {
  const hexMajor = calculateHexMajor(config.majorVersion);
  const hexMinor = calculateHexMinor(config.minorVersion);
  const revision = config.iosRevision || 21000 + config.majorVersion;

  const relevantBases = BASE_IOS_LIST.filter(b => {
    if (config.console === 'wii') return b.console === 'wii';
    if (config.console === 'wiimini') return b.console === 'wiimini' || (b.console === 'wii' && (b.ios === 56 || b.ios === 57));
    if (config.console === 'vwii') return b.console === 'vwii';
    return true;
  });

  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
  xml += `<ciosmaps ciosgroupscount="1">\n`;
  xml += `\t<ciosgroup name="d2xl-v${config.majorVersion}-${config.minorVersion}" version="${revision}" basescount="${relevantBases.length}">\n\n`;

  for (const b of relevantBases) {
    xml += `\t\t<!-- Base IOS${b.ios} v${b.version} (${b.console.toUpperCase()}) -->\n`;
    xml += `\t\t<base ios="${b.ios}" version="${b.version}" contentscount="${b.contentsCount}" modulescount="${b.modulesCount}" console="${b.console}">\n`;

    // Signature content
    xml += `\t\t\t<content id="${b.signatureContentId}" patchscount="${b.patches.filter(p => p.contentId === b.signatureContentId).length}">\n`;
    xml += `\t\t\t\t<!-- cIOS signature fields -->\n`;
    xml += `\t\t\t\t<patch offset="0x00" size="4" originalbytes="0x66,0x69,0x72,0x6d" newbytes="0x1e,0xe7,0xc1,0x05"/>\n`;
    xml += `\t\t\t\t<patch offset="0x04" size="4" originalbytes="0x77,0x61,0x72,0x65" newbytes="0x00,0x00,0x00,0x01"/>\n`;
    xml += `\t\t\t\t<patch offset="0x08" size="4" originalbytes="0x2e,0x36,0x34,0x2e" newbytes="${hexMajor}"/>\n`;
    xml += `\t\t\t\t<patch offset="0x0c" size="4" originalbytes="0x31,0x30,0x30,0x33" newbytes="0x00,0x00,0x00,0x${b.ios.toString(16).padStart(2, '0')}"/>\n`;
    xml += `\t\t\t\t<patch offset="0x10" size="16" originalbytes="0x31,0x36,0x31,0x31,0x30,0x32,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00" newbytes="0x64,0x32,0x78,0x6c,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00"/>\n`;
    xml += `\t\t\t\t<patch offset="0x20" size="16" originalbytes="0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x02,0x00,0x00" newbytes="${hexMinor}"/>\n`;
    xml += `\t\t\t\t<patch offset="0x30" size="16" originalbytes="0x61,0x64,0x6d,0x69,0x6e,0x40,0x46,0x57,0x50,0x55,0x42,0x4c,0x49,0x53,0x48,0x00" newbytes="0x16,0x1e,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00"/>\n`;
    xml += `\t\t\t</content>\n`;

    // Other patches
    for (const patch of b.patches) {
      if (patch.contentId !== b.signatureContentId) {
        xml += `\t\t\t<content id="${patch.contentId}" patchscount="1">\n`;
        xml += `\t\t\t\t<!-- ${patch.description} -->\n`;
        xml += `\t\t\t\t<patch offset="${patch.offset}" size="${patch.size}" originalbytes="${patch.originalBytes}" newbytes="${patch.newBytes}"/>\n`;
        xml += `\t\t\t</content>\n`;
      }
    }

    // Modules
    for (const m of b.modules) {
      xml += `\t\t\t<content id="${m.id}" module="${m.name}" tmdmoduleid="${m.tmdModuleId}"/>\n`;
    }

    xml += `\t\t</base>\n\n`;
  }

  xml += `\t</ciosgroup>\n`;
  xml += `</ciosmaps>\n`;
  return xml;
}

export function generateD2xBat(config: GeneratorConfig): string {
  const revision = config.iosRevision || 21000 + config.majorVersion;
  return `:: d2x-beta.bat for d2xl v${config.majorVersion}-${config.minorVersion}
:: Generated by d2xl cIOS Studio
:: Save to: modules\\More-cIOSs\\d2xl-${config.minorVersion}\\d2x-beta.bat

set ciosversion=${revision}
set d2x-beta-rev=${config.majorVersion}-${config.minorVersion}
set cIOSFamilyName=d2xl

if "%wadname%"=="" goto:endofd2xbat

:: Hash matching for ModMii installation
if /i "%wadname:~0,17%" EQU "cIOS249[56]-d2xl-v" set md5=ac0ffee1eddad70defec81005e570015
if /i "%wadname:~0,17%" EQU "cIOS250[57]-d2xl-v" set md5=ac0ffee1eddad70defec81005e570015
if /i "%wadname:~0,17%" EQU "cIOS251[58]-d2xl-v" set md5=ac0ffee1eddad70defec81005e570015
if /i "%wadname:~0,17%" EQU "cIOS249[57]-d2xl-v" set md5=ac0ffee1eddad70defec81005e570015

set md5alt=%md5%
set wadname=%wadname:~0,17%%d2x-beta-rev%
if /i "%name:~0,17%" NEQ "Advanced Download" set name=%wadname%

:endofd2xbat
`;
}

export function generateReadMe(config: GeneratorConfig): string {
  const revision = config.iosRevision || 21000 + config.majorVersion;
  return `/*
 * cIOS d2xl v${config.majorVersion} ${config.minorVersion} (Revision: ${revision})
 * Target Console: ${config.console.toUpperCase()}
 *
 * by Leseratte, based on cIOS d2x by davebaol & Waninkoko
 * Generated via d2xl cIOS Studio
 */

[ CONFIGURATION SUMMARY ]
- Console: ${config.console.toUpperCase()}
- Version: d2xl-v${config.majorVersion}-${config.minorVersion}
- Wii Mini Cover Override: ${config.features.coverOverride ? 'ENABLED (IOCTL 0xFB)' : 'DISABLED'}
- NAND Emulation: ${config.features.nandEmulation.toUpperCase()}
- IOS Reload Block: ${config.features.iosReloadBlock ? 'ENABLED' : 'DISABLED'}
- Stealth Mode: ${config.features.stealthMode ? 'ACTIVE' : 'INACTIVE'}
- 4KB Sector Size: ${config.features.virtual4kSectors ? 'ACTIVE (up to 4084 WBFS games)' : 'STANDARD'}

[ INSTALLATION SLOTS ]
${config.slots.map(s => ` - Slot ${s.slot} -> Base IOS${s.baseIOS} (Version ${s.version})`).join('\n')}

[ HOW TO INSTALL ON CONSOLE ]
Option 1: d2x-cios-installer (Recommended)
1. Download d2x-cios-installer onto SD card / USB drive at /apps/d2x-cios-installer/
2. Place the generated ciosmaps.xml into /apps/d2x-cios-installer/ciosmaps.xml
3. Launch Homebrew Channel, run the installer, select slot and base as configured above.

Option 2: ModMii (Windows)
1. Copy the generated files to ModMii's Support\\d2x-beta directory.
2. Select Beta cIOS option in ModMii and create the installable WADs.
3. Install using WiiMod, MMM, or YAWMM.
`;
}

export function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
